In [1]:
import numpy as np
import pandas as pd

In [4]:
# データを読み込みます
df = pd.read_csv('../ccc.csv')
df

        start        end     nr serial  error_code factor  print_count
0    2020/1/1   2020/1/2  500-1    aaa         1.0    NaN            1
1    2020/1/2   2020/1/7  500-2    aaa         2.0    NaN            2
2    2020/1/3   2020/2/7  500-3    aaa         4.0    NaN            3
3    2020/1/4  2020/1/10  600-1    aaa         8.0     PQ            4
4    2020/1/5  2020/2/20  600-1    aaa         3.0  Noise            5
5    2020/1/6  2020/3/20  600-1    aaa         2.0    NaN            6
6    2020/1/7   2020/1/7  701-1    bbb         4.0    NaN            7
7    2020/1/8   2020/1/2  500-1    bbb         8.0    NaN            8
8    2020/1/9   2020/1/7  500-2    bbb         1.0    NaN            9
9   2020/1/10   2020/2/7  500-3    bbb         2.0    JAM           10
10  2020/1/11  2020/1/10  600-1    bbb      7392.0     PQ           11
11  2020/1/12  2020/2/20  600-1    bbb         8.0  Noise           12
12  2020/1/13  2020/3/20  600-1    bbb         1.0    NaN           13
13  2020/1/14   2020/1/7  701-1    bbb         2.0    NaN           14
14  2020/1/15   2020/1/7  801-1    bbb         4.0    JAM           15
15  2020/1/16   2020/1/7  801-1    ccc         8.0    JAM           16
16  2020/1/17   2020/1/7  801-1    ccc         1.0    JAM           17
17  2020/1/18   2020/2/7  600-1    eee         NaN    NaN           18
18  2020/1/19  2020/1/10  600-1    eee         NaN    NaN           19
19  2020/1/20  2020/2/20  600-1    eee         NaN    NaN           20
20  2020/1/21  2020/3/20  701-1    eee         NaN    NaN           21
21  2020/1/22   2020/1/7  801-1    eee         NaN    NaN           22
22  2020/1/23   2020/1/7  801-1    eee         NaN    JAM           23
23  2020/1/24   2020/1/7  801-1    eee         NaN    JAM           24

In [5]:
# エラー発生時のインデックスリストを作成
index_list = df[~df.factor.isnull()].index.to_list()
index_list

[3, 4, 9, 10, 11, 14, 15, 16, 22, 23]

In [6]:
# エラー発生前後50行のインデックスリストを作成
index_max = len(df)
hold_list = []
for i in index_list:
    for j in range(-1,2):
        if i+j>=0 and i+j<index_max:
            hold_list.append(i+j)
hold_list = list(set(hold_list))
hold_list

[2, 3, 4, 5, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 21, 22, 23]

In [7]:
# エラー発生前後50行のデータのみを残す
df.loc[df.index[hold_list],'Hold'] = 1
df = df.dropna(subset=['Hold'])
df = df.drop('Hold',axis=1)
df

        start        end     nr serial  error_code factor  print_count
2    2020/1/3   2020/2/7  500-3    aaa         4.0    NaN            3
3    2020/1/4  2020/1/10  600-1    aaa         8.0     PQ            4
4    2020/1/5  2020/2/20  600-1    aaa         3.0  Noise            5
5    2020/1/6  2020/3/20  600-1    aaa         2.0    NaN            6
8    2020/1/9   2020/1/7  500-2    bbb         1.0    NaN            9
9   2020/1/10   2020/2/7  500-3    bbb         2.0    JAM           10
10  2020/1/11  2020/1/10  600-1    bbb      7392.0     PQ           11
11  2020/1/12  2020/2/20  600-1    bbb         8.0  Noise           12
12  2020/1/13  2020/3/20  600-1    bbb         1.0    NaN           13
13  2020/1/14   2020/1/7  701-1    bbb         2.0    NaN           14
14  2020/1/15   2020/1/7  801-1    bbb         4.0    JAM           15
15  2020/1/16   2020/1/7  801-1    ccc         8.0    JAM           16
16  2020/1/17   2020/1/7  801-1    ccc         1.0    JAM           17
17  2020/1/18   2020/2/7  600-1    eee         NaN    NaN           18
21  2020/1/22   2020/1/7  801-1    eee         NaN    NaN           22
22  2020/1/23   2020/1/7  801-1    eee         NaN    JAM           23
23  2020/1/24   2020/1/7  801-1    eee         NaN    JAM           24