In [11]:
import numpy as np
import pandas as pd

In [12]:
# データを読み込みます
df = pd.read_csv('../bbb.csv')
df.head()

      start        end     nr serial error_code factor  print_count
0  2020/1/1   2020/1/2  500-1    aaa         寿命     PQ            1
1  2020/1/2   2020/1/7  500-2    aaa         新品     PQ            2
2  2020/1/3   2020/2/7  500-3    aaa         寿命    JAM            3
3  2020/1/4  2020/1/10  600-1    aaa         寿命     PQ            4
4  2020/1/5  2020/2/20  600-1    aaa         新品  Noise            5

In [17]:
factor_dict = pd.read_csv('要因.csv', index_col=0).to_dict()['CAUSE']
factor_dict

{1: 'あ',
 2: 'い',
 3: 'う',
 4: 'え',
 5: 'お',
 6: 'か',
 7: 'き',
 8: 'く',
 9: 'け',
 10: 'こ',
 11: 'さ',
 12: 'し',
 13: 'す',
 14: 'せ',
 15: 'そ',
 16: 'た'}

In [18]:
df = pd.read_csv('test1.csv')
df

        start        end     nr serial  error_code factor  print_count
0    2020/1/1   2020/1/2  500-1    aaa           1     PQ            1
1    2020/1/2   2020/1/7  500-2    aaa           2     PQ            2
2    2020/1/3   2020/2/7  500-3    aaa           4    JAM            3
3    2020/1/4  2020/1/10  600-1    aaa           8     PQ            4
4    2020/1/5  2020/2/20  600-1    aaa           3  Noise            5
5    2020/1/6  2020/3/20  600-1    aaa           2  Noise            6
6    2020/1/7   2020/1/7  701-1    bbb           4    JAM            7
7    2020/1/8   2020/1/2  500-1    bbb           8     PQ            8
8    2020/1/9   2020/1/7  500-2    bbb           1    JAM            9
9   2020/1/10   2020/2/7  500-3    bbb           2    JAM           10
10  2020/1/11  2020/1/10  600-1    bbb        7392     PQ           11
11  2020/1/12  2020/2/20  600-1    bbb           8  Noise           12
12  2020/1/13  2020/3/20  600-1    bbb           1  Noise           13
13  2020/1/14   2020/1/7  701-1    bbb           2    JAM           14
14  2020/1/15   2020/1/7  801-1    bbb           4    JAM           15
15  2020/1/16   2020/1/7  801-1    ccc           8    JAM           16
16  2020/1/17   2020/1/7  801-1    ccc           1    JAM           17

In [19]:
def func(x,dic):
    factor = ''
    if bin(x & 0b1) == bin(2**0):
        if len(factor)==0:
            factor += dic[1]
        else:
            factor += '+'+dic[1]
    if bin(x & 0b10) == bin(2**1):
        if len(factor)==0:
            factor += dic[2]
        else:
            factor += '+'+dic[2]
    if bin(x & 0b100) == bin(2**2):
        if len(factor)==0:
            factor += dic[3]
        else:
            factor += '+'+dic[3]
    if bin(x & 0b1000) == bin(2**3):
        if len(factor)==0:
            factor += dic[4]
        else:
            factor += '+'+dic[4]
    if bin(x & 0b10000) == bin(2**4):
        if len(factor)==0:
            factor += dic[5]
        else:
            factor += '+'+dic[5]
    if bin(x & 0b100000) == bin(2**5):
        if len(factor)==0:
            factor += dic[6]
        else:
            factor += '+'+dic[6]
    if bin(x & 0b1000000) == bin(2**6):
        if len(factor)==0:
            factor += dic[7]
        else:
            factor += '+'+dic[7]
    if bin(x & 0b10000000) == bin(2**7):
        if len(factor)==0:
            factor += dic[8]
        else:
            factor += '+'+dic[8]
    if bin(x & 0b100000000) == bin(2**8):
        if len(factor)==0:
            factor += dic[9]
        else:
            factor += '+'+dic[9]
    if bin(x & 0b1000000000) == bin(2**9):
        if len(factor)==0:
            factor += dic[10]
        else:
            factor += '+'+dic[10]
    if bin(x & 0b10000000000) == bin(2**10):
        if len(factor)==0:
            factor += dic[11]
        else:
            factor += '+'+dic[11]
    if bin(x & 0b100000000000) == bin(2**11):
        if len(factor)==0:
            factor += dic[12]
        else:
            factor += '+'+dic[12]
    if bin(x & 0b1000000000000) == bin(2**12):
        if len(factor)==0:
            factor += dic[13]
        else:
            factor += '+'+dic[13]
    if bin(x & 0b10000000000000) == bin(2**13):
        if len(factor)==0:
            factor += dic[14]
        else:
            factor += '+'+dic[14]
    if bin(x & 0b100000000000000) == bin(2**14):
        if len(factor)==0:
            factor += dic[15]
        else:
            factor += '+'+dic[15]
    if bin(x & 0b1000000000000000) == bin(2**15):
        if len(factor)==0:
            factor += dic[16]
        else:
            factor += '+'+dic[16]
    return factor
    

df['CPR_Factor'] = df.error_code.apply(func, dic=factor_dict)
df

,start,end,nr,serial,error_code,factor,print_count,CPR_Factor
0,2020/1/1,2020/1/2,500-1,aaa,1,PQ,1,あ
1,2020/1/2,2020/1/7,500-2,aaa,2,PQ,2,い
2,2020/1/3,2020/2/7,500-3,aaa,4,JAM,3,う
3,2020/1/4,2020/1/10,600-1,aaa,8,PQ,4,え
4,2020/1/5,2020/2/20,600-1,aaa,3,Noise,5,あ+い
5,2020/1/6,2020/3/20,600-1,aaa,2,Noise,6,い
6,2020/1/7,2020/1/7,701-1,bbb,4,JAM,7,う
7,2020/1/8,2020/1/2,500-1,bbb,8,PQ,8,え
8,2020/1/9,2020/1/7,500-2,bbb,1,JAM,9,あ
9,2020/1/10,2020/2/7,500-3,bbb,2,JAM,10,い
10,2020/1/11,2020/1/10,600-1,bbb,7392,PQ,11,か+き+く+さ+し+す
11,2020/1/12,2020/2/20,600-1,bbb,8,Noise,12,え
12,2020/1/13,2020/3/20,600-1,bbb,1,Noise,13,あ
13,2020/1/14,2020/1/7,701-1,bbb,2,JAM,14,い
14,2020/1/15,2020/1/7,801-1,bbb,4,JAM,15,う
15,2020/1/16,2020/1/7,801-1,ccc,8,JAM,16,え
16,2020/1/17,2020/1/7,801-1,ccc,1,JAM,17,あ